env:
  node: true
extends:
  - eslint:recommended
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules: 
  no-console: off
  no-use-before-define: off
  arrow-body-style: off
ignorePatterns: ["src/node_modules/*"]
